server:
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: moobeing
  servlet:
    multipart:
      max-file-size: 50MB  # 파일당 최대 크기
      max-request-size: 50MB  # 전체 요청의 최대 크기


  sql:
    init:
      mode: always

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST}:${PORT}/${DATABASE_NAME}?${OPTIONS}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      open-in-view: true

  logging:
    level:
      com.app: debug

SSAFY_APIKEY: ${SSAFY_APIKEY}

openai:
  api:
    key: ${OPENAI_KEY}